<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>BoxLang Template</string>
	<key>scopeName</key>
	<string>source.boxlang.template</string>
	<key>fileTypes</key>
	<array>
		<string>bxm</string>
	</array>
	<key>uuid</key>
	<string>1A6EB03E-FD9E-4BFC-8C85-ED8D2399DB2F</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#bx-script</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#bx-output</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#bx-if</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#bx-switch</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#bx-try</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#bx-while</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#bx-function</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#bx-components</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#interpolation</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#html-content</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.block.boxlang.template</string>
					<key>begin</key>
					<string>&lt;!---</string>
					<key>end</key>
					<string>---&gt;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>comment.block.boxlang.template</string>
							<key>begin</key>
							<string>&lt;!---</string>
							<key>end</key>
							<string>---&gt;</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.block.html</string>
					<key>begin</key>
					<string>&lt;!--(?!-)</string>
					<key>end</key>
					<string>--&gt;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bad-comments-or-CDATA.html</string>
							<key>match</key>
							<string>--</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>bx-script</key>
		<dict>
			<key>name</key>
			<string>meta.embedded.block.boxlang.script</string>
			<key>begin</key>
			<string>(&lt;)(bx:script)(\s[^&gt;]*)?+(&gt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.boxlang</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.script.boxlang</string>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag-attributes</string>
						</dict>
					</array>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.boxlang</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&lt;/)\s*(bx:script)\s*(&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.boxlang</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.script.boxlang</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.boxlang</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.boxlang</string>
				</dict>
			</array>
		</dict>
		<key>bx-components</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#bx-generic</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bx-self-closing</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bx-closing</string>
				</dict>
			</array>
		</dict>
		<key>bx-output</key>
		<dict>
			<key>name</key>
			<string>meta.tag.output.boxlang</string>
			<key>begin</key>
			<string>(&lt;)(bx:output)(\s[^&gt;]*)?+(&gt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.boxlang</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.output.boxlang</string>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag-attributes</string>
						</dict>
					</array>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.boxlang</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&lt;/)\s*(bx:output)\s*(&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.boxlang</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.output.boxlang</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.boxlang</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#interpolation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bx-components</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#html-content</string>
				</dict>
			</array>
		</dict>
		<key>bx-if</key>
		<dict>
			<key>name</key>
			<string>meta.tag.conditional.boxlang</string>
			<key>begin</key>
			<string>(&lt;)(bx:if)(\s[^&gt;]*)?+(&gt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.boxlang</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.conditional.boxlang</string>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag-attributes</string>
						</dict>
					</array>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.boxlang</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&lt;/)\s*(bx:if)\s*(&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.boxlang</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.conditional.boxlang</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.boxlang</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#bx-elseif</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bx-else</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#interpolation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bx-components</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#html-content</string>
				</dict>
			</array>
		</dict>
		<key>bx-elseif</key>
		<dict>
			<key>name</key>
			<string>meta.tag.conditional.boxlang</string>
			<key>match</key>
			<string>(&lt;)(bx:elseif)(\s[^&gt;]*)?+(&gt;)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.boxlang</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.conditional.boxlang</string>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag-attributes</string>
						</dict>
					</array>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.boxlang</string>
				</dict>
			</dict>
		</dict>
		<key>bx-else</key>
		<dict>
			<key>name</key>
			<string>meta.tag.conditional.boxlang</string>
			<key>match</key>
			<string>(&lt;)(bx:else)(\s[^&gt;]*)?+(/?&gt;|&gt;)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.boxlang</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.conditional.boxlang</string>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag-attributes</string>
						</dict>
					</array>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.boxlang</string>
				</dict>
			</dict>
		</dict>
		<key>bx-switch</key>
		<dict>
			<key>name</key>
			<string>meta.tag.switch.boxlang</string>
			<key>begin</key>
			<string>(&lt;)(bx:switch)(\s[^&gt;]*)?+(&gt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.boxlang</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.switch.boxlang</string>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag-attributes</string>
						</dict>
					</array>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.boxlang</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&lt;/)\s*(bx:switch)\s*(&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.boxlang</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.switch.boxlang</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.boxlang</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#bx-case</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bx-defaultcase</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#interpolation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bx-components</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#html-content</string>
				</dict>
			</array>
		</dict>
		<key>bx-case</key>
		<dict>
			<key>name</key>
			<string>meta.tag.case.boxlang</string>
			<key>begin</key>
			<string>(&lt;)(bx:case)(\s[^&gt;]*)?+(&gt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.boxlang</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.case.boxlang</string>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag-attributes</string>
						</dict>
					</array>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.boxlang</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&lt;/)\s*(bx:case)\s*(&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.boxlang</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.case.boxlang</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.boxlang</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$base</string>
				</dict>
			</array>
		</dict>
		<key>bx-defaultcase</key>
		<dict>
			<key>name</key>
			<string>meta.tag.defaultcase.boxlang</string>
			<key>begin</key>
			<string>(&lt;)(bx:defaultcase)(\s*)?(&gt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.boxlang</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.defaultcase.boxlang</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>text</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.boxlang</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&lt;/)\s*(bx:defaultcase)\s*(&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.boxlang</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.defaultcase.boxlang</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.boxlang</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$base</string>
				</dict>
			</array>
		</dict>
		<key>bx-try</key>
		<dict>
			<key>name</key>
			<string>meta.tag.try.boxlang</string>
			<key>begin</key>
			<string>(&lt;)(bx:try)(\s*)?(&gt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.boxlang</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.try.boxlang</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>text</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.boxlang</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&lt;/)\s*(bx:try)\s*(&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.boxlang</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.try.boxlang</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.boxlang</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#bx-catch</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bx-finally</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$base</string>
				</dict>
			</array>
		</dict>
		<key>bx-catch</key>
		<dict>
			<key>name</key>
			<string>meta.tag.catch.boxlang</string>
			<key>begin</key>
			<string>(&lt;)(bx:catch)(\s[^&gt;]*)?+(&gt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.boxlang</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.catch.boxlang</string>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag-attributes</string>
						</dict>
					</array>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.boxlang</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&lt;/)\s*(bx:catch)\s*(&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.boxlang</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.catch.boxlang</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.boxlang</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$base</string>
				</dict>
			</array>
		</dict>
		<key>bx-finally</key>
		<dict>
			<key>name</key>
			<string>meta.tag.finally.boxlang</string>
			<key>begin</key>
			<string>(&lt;)(bx:finally)(\s*)?(&gt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.boxlang</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.finally.boxlang</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>text</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.boxlang</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&lt;/)\s*(bx:finally)\s*(&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.boxlang</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.finally.boxlang</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.boxlang</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$base</string>
				</dict>
			</array>
		</dict>
		<key>bx-while</key>
		<dict>
			<key>name</key>
			<string>meta.tag.while.boxlang</string>
			<key>begin</key>
			<string>(&lt;)(bx:while)(\s[^&gt;]*)?+(&gt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.boxlang</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.while.boxlang</string>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag-attributes</string>
						</dict>
					</array>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.boxlang</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&lt;/)\s*(bx:while)\s*(&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.boxlang</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.while.boxlang</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.boxlang</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$base</string>
				</dict>
			</array>
		</dict>
		<key>bx-function</key>
		<dict>
			<key>name</key>
			<string>meta.tag.function.boxlang</string>
			<key>begin</key>
			<string>(&lt;)(bx:function)(\s[^&gt;]*)?+(&gt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.boxlang</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.function.boxlang</string>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag-attributes</string>
						</dict>
					</array>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.boxlang</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&lt;/)\s*(bx:function)\s*(&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.boxlang</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.function.boxlang</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.boxlang</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#bx-argument</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$base</string>
				</dict>
			</array>
		</dict>
		<key>bx-argument</key>
		<dict>
			<key>name</key>
			<string>meta.tag.argument.boxlang</string>
			<key>match</key>
			<string>(&lt;)(bx:argument)(\s[^&gt;]*)?+(/?&gt;|&gt;)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.boxlang</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.argument.boxlang</string>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag-attributes</string>
						</dict>
					</array>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.boxlang</string>
				</dict>
			</dict>
		</dict>
		<key>bx-self-closing</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.tag.self-closing.boxlang</string>
					<key>match</key>
					<string>(&lt;)(bx:([a-zA-Z_][a-zA-Z0-9_\-]*))(\s[^&gt;]*)?+(/&gt;)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.boxlang</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.boxlang</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.boxlang</string>
						</dict>
						<key>4</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#tag-attributes</string>
								</dict>
							</array>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.boxlang</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>bx-generic</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.tag.generic.boxlang</string>
					<key>begin</key>
					<string>(&lt;)(bx:([a-zA-Z_][a-zA-Z0-9_\-]*))(?=\s|&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.boxlang</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.boxlang</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.boxlang</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(&lt;/)\s*(bx:[a-zA-Z_][a-zA-Z0-9_\-]*)\s*(&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.boxlang</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.boxlang</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.boxlang</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>meta.tag.generic.opening.boxlang</string>
							<key>begin</key>
							<string>\G</string>
							<key>end</key>
							<string>(&gt;)</string>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.boxlang</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#tag-attributes</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>$base</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>tag-attributes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.attribute.boxlang</string>
					<key>begin</key>
					<string>([a-zA-Z_][a-zA-Z0-9_\-]*)\s*(=)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.boxlang</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.key-value.boxlang</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\s|&gt;|/?&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#attribute-values</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.boxlang</string>
					<key>match</key>
					<string>[a-zA-Z_][a-zA-Z0-9_\-]*</string>
				</dict>
			</array>
		</dict>
		<key>attribute-values</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.quoted.double.boxlang</string>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#interpolation</string>
						</dict>
						<dict>
							<key>name</key>
							<string>constant.character.escape.boxlang</string>
							<key>match</key>
							<string>##</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>name</key>
					<string>string.quoted.single.boxlang</string>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>'</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#interpolation</string>
						</dict>
						<dict>
							<key>name</key>
							<string>constant.character.escape.boxlang</string>
							<key>match</key>
							<string>##</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#interpolation</string>
				</dict>
				<dict>
					<key>name</key>
					<string>string.unquoted.boxlang</string>
					<key>match</key>
					<string>[^\s&gt;"']+</string>
				</dict>
			</array>
		</dict>
		<key>interpolation</key>
		<dict>
			<key>name</key>
			<string>meta.embedded.line.boxlang</string>
			<key>begin</key>
			<string>#</string>
			<key>end</key>
			<string>#</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.embedded.begin.boxlang</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.embedded.end.boxlang</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#expressions</string>
				</dict>
			</array>
		</dict>
		<key>expressions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numbers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function-calls</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.control.boxlang</string>
					<key>match</key>
					<string>(?i)\b(if|else|elseif|switch|case|default|for|while|do|break|continue|return|try|catch|finally|throw|rethrow)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.other.boxlang</string>
					<key>match</key>
					<string>(?i)\b(import|include|as|in|instanceof|castas|does|not|contain|contains|than|to|when|assert|param|abort|exit|lock|thread|transaction)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>storage.modifier.boxlang</string>
					<key>match</key>
					<string>(?i)\b(public|private|remote|package|static|final|abstract|required)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>storage.type.boxlang</string>
					<key>match</key>
					<string>(?i)\b(class|interface|function|property|var)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>storage.type.primitive.boxlang</string>
					<key>match</key>
					<string>(?i)\b(any|array|boolean|numeric|query|string|struct)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.boxlang</string>
					<key>match</key>
					<string>(?i)\b(true|false|null)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>variable.language.scope.boxlang</string>
					<key>match</key>
					<string>(?i)\b(variables|request|server|application|session|client|form|url|cgi|cookie)\b</string>
				</dict>
			</array>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.operator.logical.boxlang</string>
					<key>match</key>
					<string>(?i)\b(and|or|not|xor|eqv|imp)\b|&amp;&amp;|\|\||!</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.comparison.boxlang</string>
					<key>match</key>
					<string>(?i)\b(eq|equal|neq|gt|gte|ge|lt|lte|le|is)\b|==|!=|&lt;&gt;|&gt;=|&lt;=|&gt;|&lt;|===</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.arithmetic.boxlang</string>
					<key>match</key>
					<string>\+\+|--|\+|\-|\*|/|%|\\|\^|(?i)\bmod\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.boxlang</string>
					<key>match</key>
					<string>=|\+=|\-=|\*=|/=|%=|&amp;=</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.string.boxlang</string>
					<key>match</key>
					<string>&amp;</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.ternary.boxlang</string>
					<key>match</key>
					<string>\?:|\?|:</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.bitwise.boxlang</string>
					<key>match</key>
					<string>\bb[&amp;|^~]\b|\bb&lt;&lt;\b|\bb&gt;&gt;\b|\bb&gt;&gt;&gt;\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.access.boxlang</string>
					<key>match</key>
					<string>\.|::|\\?\\.</string>
				</dict>
			</array>
		</dict>
		<key>numbers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.numeric.float.boxlang</string>
					<key>match</key>
					<string>\b\d+\.\d+([eE][+-]?\d+)?\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.float.boxlang</string>
					<key>match</key>
					<string>\.\d+([eE][+-]?\d+)?\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.integer.boxlang</string>
					<key>match</key>
					<string>\b\d+([_]?\d)*\b</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.quoted.double.boxlang</string>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>constant.character.escape.boxlang</string>
							<key>match</key>
							<string>##</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#interpolation</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>name</key>
					<string>string.quoted.single.boxlang</string>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>'</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>constant.character.escape.boxlang</string>
							<key>match</key>
							<string>##</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#interpolation</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>function-calls</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.function-call.boxlang</string>
					<key>match</key>
					<string>([a-zA-Z_][a-zA-Z0-9_]*)\s*(\()</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.boxlang</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.begin.boxlang</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>variables</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>variable.other.boxlang</string>
					<key>match</key>
					<string>\b[a-zA-Z_][a-zA-Z0-9_]*\b</string>
				</dict>
			</array>
		</dict>
		<key>html-content</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#html-doctype</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#html-tag</string>
				</dict>
				<dict>
					<key>name</key>
					<string>text.html.basic</string>
					<key>match</key>
					<string>[^&lt;#]+</string>
				</dict>
			</array>
		</dict>
		<key>html-doctype</key>
		<dict>
			<key>name</key>
			<string>meta.tag.sgml.doctype.html</string>
			<key>begin</key>
			<string>&lt;!(?i:DOCTYPE)</string>
			<key>end</key>
			<string>&gt;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.quoted.double.doctype.identifiers-and-DTDs.html</string>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
				</dict>
			</array>
		</dict>
		<key>html-tag</key>
		<dict>
			<key>name</key>
			<string>meta.tag.any.html</string>
			<key>begin</key>
			<string>&lt;(?!bx:|/bx:|#)</string>
			<key>end</key>
			<string>&gt;</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.html</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.html</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>entity.name.tag.html</string>
					<key>match</key>
					<string>\G/?[a-zA-Z][a-zA-Z0-9-]*</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#html-attribute</string>
				</dict>
			</array>
		</dict>
		<key>html-attribute</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.attribute-with-value.html</string>
					<key>begin</key>
					<string>\b([a-zA-Z-]+)(=)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.key-value.html</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\s|/?&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#html-attribute-value</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.html</string>
					<key>match</key>
					<string>\b[a-zA-Z-]+</string>
				</dict>
			</array>
		</dict>
		<key>html-attribute-value</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.quoted.double.html</string>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.html</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.html</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>constant.character.entity.html</string>
							<key>match</key>
							<string>&amp;[a-zA-Z0-9]+;</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>name</key>
					<string>string.quoted.single.html</string>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.html</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.html</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>constant.character.entity.html</string>
							<key>match</key>
							<string>&amp;[a-zA-Z0-9]+;</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>name</key>
					<string>string.unquoted.html</string>
					<key>match</key>
					<string>[^\s/&gt;]+</string>
				</dict>
			</array>
		</dict>
		<key>bx-no-body</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.tag.no-body.boxlang</string>
					<key>match</key>
					<string>(&lt;)(bx:([a-zA-Z_][a-zA-Z0-9_\-]*))(\s[^&gt;]*)?+(&gt;)(?!\s*&lt;/bx:)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.boxlang</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.boxlang</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.boxlang</string>
						</dict>
						<key>4</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#tag-attributes</string>
								</dict>
							</array>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.boxlang</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
	</dict>
</dict>
</plist>